#!/bin/bash
set -xeo pipefail

INSTALL_EDITORS=(neovim nano helix)


pacman -S --needed $INSTALL_EDITORS 
pacman -S --needed arch-install-scripts


BEFORE_PWD=$(pwd)

curl -o archlinux-bootstrap-2026.03.01-x86_64.tar.zst https://mirrors.ukfast.co.uk/sites/archlinux.org/iso/2026.03.01/archlinux-bootstrap-2026.03.01-x86_64.tar.zst


EXTRACT_DIR=$(mktemp -d)
cd $EXTRACT_DIR
tar xf $BEFORE_PWD/archlinux-bootstrap-2026.03.01-x86_64.tar.zst --numeric-owner

CHROOT_DIR=$EXTRACT_DIR/root.x86_64

mount --bind $CHROOT_DIR $CHROOT_DIR

# initialise pacman keyring
arch-chroot $CHROOT_DIR -- pacman-key --init
arch-chroot $CHROOT_DIR -- pacman-key --populate

# create pacman mirrors

cat >> $CHROOT_DIR/etc/pacman.d/mirrorlist << EOF
Server = https://mirrors.ukfast.co.uk/sites/archlinux.org/$repo/os/$arch
Server = https://www.mirrorservice.org/sites/ftp.archlinux.org/$repo/os/$arch
Server = https://mirror.server.net/archlinux/$repo/os/$arch
Server = https://lon.mirror.rackspace.com/archlinux/$repo/os/$arch
EOF

# setup networking

cat > $CHROOT_DIR/etc/systemd/network/89-ethernet.network << EOF
[Match]
Kind=!*
Type=ether

[Network]
DHCP=yes

[DHCPv4]
UseDNS=true

[DHCPv6]
UseDNS=true
EOF


arch-chroot $CHROOT_DIR -- pacman -S --needed $INSTALL_EDITORS

# set the locale, time, hostname
echo "LANG=en_GB.UTF-8" > $CHROOT_DIR/etc/locale.conf
arch-chroot $CHROOT_DIR -- locale-gen

arch-chroot $CHROOT_DIR -- ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime
arch-chroot $CHROOT_DIR -- hwclock --systohc

echo duscc > $CHROOT_DIR/etc/hostname


echo "Set the root password for the vm"
arch-chroot $CHROOT_DIR -- passwd



cd $BEFORE_PWD

IMG_FILE=root.img

dd if=/dev/zero of=$IMG_FILE bs=1M count=4096

echo Please setup the partitions with 1gb EFI, 3gb Linux Root x86_64
sleep 5

cfdisk $IMG_FILE

IMG_LO=$(losetup --find --show --part-scan root.img)

mkfs.ext4 -L ROOT ${IMG_LO}p2
mkfs.fat -F 32 -n BOOT ${IMG_LO}p1

# mount boot partition
mount ${IMG_LO}p2 /mnt
cp -rp $EXTRACT_DIR/root.x86_64/* /mnt

mkdir -p /mnt/boot

# mount boot partition
mount ${IMG_LO}p1 /mnt

arch-chroot /mnt -- pacman -S linux dracut sudo

umount -R /mnt


losetup -D

exit
